#!/bin/sh

# This script displays shuffled output of $XDG_MUSIC_DIR in dmenu
# You can type "/." to play all the songs in the directory

# sxhkd example:
# XF86Tools
# 	bp-play

selection=$(find "$XDG_MUSIC_DIR" -name "*.mp3" -exec basename {} \; | shuf - | dmenu -i -l 20)

[ -n "$selection" ] && echo "loadfile \"$XDG_MUSIC_DIR/$selection\" append-play" | socat - '/tmp/mpv-socket'
