#!/bin/sh

# This script displays shuffled output of $XDG_MUSIC_DIR in dmenu
# You can type "/." to play all the songs in the directory

# sxhkd example:
# XF86Tools
# 	bp-play

selection=$(mpc ls | shuf - | \
	dmenu -bw 1 -c -i -l 20 -sb '#6F6864' -nb '#282828' -nf '#F4B92F' -sf '#F4B92F')

[ -n "$selection" ] && mpc add "$selection"
