#!/bin/sh

# This script let's you mute or change volume
# Available arguments are "mute", "+ANYNUMBER", "-ANYNUMBER" and "ANYNUMBER"

# sxhkd example:
# XF86Audio{RaiseVolume,LowerVolume,Mute}
# 	bp-vol {+5,-5,mute}


mpc volume "$1"
